# Generated by Django 6.0 on 2026-01-28 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coredata', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ball_number', models.PositiveIntegerField(help_text='Sequential delivery order within the innings')),
                ('over_number', models.PositiveIntegerField(help_text='1-based over number')),
                ('ball_in_over', models.PositiveIntegerField(help_text='1-based delivery count within the over')),
                ('is_legal_delivery', models.BooleanField(default=True, help_text='Counts towards legal ball count')),
                ('runs_off_bat', models.PositiveSmallIntegerField(default=0)),
                ('extra_runs', models.PositiveSmallIntegerField(default=0)),
                ('bye_runs', models.PositiveSmallIntegerField(default=0)),
                ('leg_bye_runs', models.PositiveSmallIntegerField(default=0)),
                ('wide_runs', models.PositiveSmallIntegerField(default=0)),
                ('no_ball_runs', models.PositiveSmallIntegerField(default=0)),
                ('penalty_runs', models.PositiveSmallIntegerField(default=0)),
                ('overthrow_runs', models.PositiveSmallIntegerField(default=0)),
                ('is_boundary', models.BooleanField(default=False)),
                ('is_short_run', models.BooleanField(default=False)),
                ('no_ball_type', models.CharField(blank=True, help_text='overstep / height / free-hit etc.', max_length=20, null=True)),
                ('edit_later', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_batted', to='coredata.team')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_bowled', to='coredata.player')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_bowled', to='coredata.team')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='matches.innings')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='matches.match')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_non_striker', to='coredata.player')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_faced', to='coredata.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balls_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['innings', 'ball_number'],
            },
        ),
        migrations.CreateModel(
            name='BallAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_type', models.CharField(blank=True, help_text='Yorker, bouncer, good length, full toss, etc.', max_length=30, null=True)),
                ('crease_movement', models.CharField(blank=True, help_text='Bowler movement on the crease', max_length=30, null=True)),
                ('shot_connection', models.CharField(blank=True, help_text='Early / Late / Perfect timing', max_length=30, null=True)),
                ('bat_subject', models.CharField(blank=True, help_text='Edge / Middle / Toe / Handle', max_length=30, null=True)),
                ('stroke', models.CharField(blank=True, help_text='Drive, cut, pull, sweep, etc.', max_length=30, null=True)),
                ('keeper_activity', models.CharField(blank=True, help_text='Keeper movement or action', max_length=50, null=True)),
                ('fielding_activity', models.CharField(blank=True, help_text='Fielding action involved', max_length=50, null=True)),
                ('batsman_activity', models.CharField(blank=True, help_text='Footwork, trigger movement', max_length=50, null=True)),
                ('umpire_activity', models.CharField(blank=True, help_text='Signal, position, interaction', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ball', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='scoring.ball')),
            ],
        ),
        migrations.CreateModel(
            name='BallReleaseData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bowler_release_x', models.FloatField(blank=True, help_text='Normalized X coordinate of bowler release point', null=True)),
                ('bowler_release_y', models.FloatField(blank=True, help_text='Normalized Y coordinate of bowler release point', null=True)),
                ('bowler_release_position', models.CharField(blank=True, help_text='Encoded release position (wide/close/over/round arm etc.)', max_length=30, null=True)),
                ('wicket_keeper_position', models.CharField(blank=True, help_text='Standing up / back', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ball', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_data', to='scoring.ball')),
            ],
        ),
        migrations.CreateModel(
            name='BallSpatialOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shot_zone_x', models.FloatField(blank=True, help_text='Normalized X coordinate of shot impact on pitch', null=True)),
                ('shot_zone_y', models.FloatField(blank=True, help_text='Normalized Y coordinate of shot impact on pitch', null=True)),
                ('wagon_wheel_x', models.FloatField(blank=True, help_text='Normalized X coordinate for wagon wheel', null=True)),
                ('wagon_wheel_y', models.FloatField(blank=True, help_text='Normalized Y coordinate for wagon wheel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ball', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_outcome', to='scoring.ball')),
            ],
        ),
        migrations.CreateModel(
            name='BallTrajectory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_index', models.PositiveIntegerField(help_text='Order of this point in the trajectory sequence')),
                ('x', models.FloatField(help_text='Normalized X coordinate of the ball')),
                ('y', models.FloatField(help_text='Normalized Y coordinate of the ball')),
                ('z', models.FloatField(blank=True, help_text='Optional Z coordinate (height)', null=True)),
                ('time_ms', models.PositiveIntegerField(blank=True, help_text='Milliseconds since ball release', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectory_points', to='scoring.ball')),
            ],
            options={
                'ordering': ['sequence_index'],
            },
        ),
        migrations.CreateModel(
            name='BallVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_source_id', models.CharField(help_text='Identifier for the match video source', max_length=100)),
                ('video_start_ms', models.PositiveIntegerField(help_text='Start timestamp of the ball in milliseconds')),
                ('video_end_ms', models.PositiveIntegerField(help_text='End timestamp of the ball in milliseconds')),
                ('camera_angle', models.CharField(blank=True, help_text='Broadcast / end-on / side-on etc.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ball', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='scoring.ball')),
            ],
        ),
        migrations.CreateModel(
            name='BallWicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wicket_type', models.CharField(choices=[('BOWLED', 'Bowled'), ('LBW', 'LBW'), ('CAUGHT', 'Caught'), ('RUN_OUT', 'Run Out'), ('STUMPED', 'Stumped'), ('HIT_WICKET', 'Hit Wicket'), ('RETIRED_HURT', 'Retired Hurt'), ('OBSTRUCTING_FIELD', 'Obstructing the Field'), ('HANDLED_BALL', 'Handled the Ball'), ('TIMED_OUT', 'Timed Out')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ball', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wicket', to='scoring.ball')),
                ('caught_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catches_taken', to='coredata.player')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wickets_credited', to='coredata.player')),
                ('dismissed_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dismissals', to='coredata.player')),
                ('run_out_fielder_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='run_outs_primary', to='coredata.player')),
                ('run_out_fielder_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='run_outs_secondary', to='coredata.player')),
                ('stumped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stumpings_made', to='coredata.player')),
            ],
        ),
        migrations.CreateModel(
            name='BatterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveSmallIntegerField(default=0)),
                ('sixes', models.PositiveSmallIntegerField(default=0)),
                ('is_out', models.BooleanField(default=False)),
                ('dismissal_ball', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.ball')),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batter_stats', to='matches.innings')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.player')),
            ],
        ),
        migrations.CreateModel(
            name='BowlerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balls', models.PositiveIntegerField(default=0)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('wides', models.PositiveSmallIntegerField(default=0)),
                ('no_balls', models.PositiveSmallIntegerField(default=0)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler_stats', to='matches.innings')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.player')),
            ],
        ),
        migrations.CreateModel(
            name='InningsAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('legal_balls', models.PositiveIntegerField(default=0)),
                ('completed_overs', models.PositiveIntegerField(default=0)),
                ('extras', models.PositiveIntegerField(default=0)),
                ('is_chasing', models.BooleanField(default=False)),
                ('target_runs', models.PositiveIntegerField(blank=True, help_text='Target runs for chase (if applicable)', null=True)),
                ('revised_target_runs', models.PositiveIntegerField(blank=True, help_text='DLS / manual revised target', null=True)),
                ('max_overs', models.PositiveSmallIntegerField(blank=True, help_text='Revised max overs for innings (interruptions)', null=True)),
                ('target_achieved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coredata.player')),
                ('current_non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coredata.player')),
                ('current_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coredata.player')),
                ('innings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='matches.innings')),
                ('last_ball', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scoring.ball')),
            ],
        ),
        migrations.AddIndex(
            model_name='ball',
            index=models.Index(fields=['match', 'innings'], name='scoring_bal_match_i_ac0902_idx'),
        ),
        migrations.AddIndex(
            model_name='ball',
            index=models.Index(fields=['innings', 'ball_number'], name='scoring_bal_innings_c72477_idx'),
        ),
        migrations.AddIndex(
            model_name='ball',
            index=models.Index(fields=['bowler'], name='scoring_bal_bowler__6adccb_idx'),
        ),
        migrations.AddIndex(
            model_name='ball',
            index=models.Index(fields=['striker'], name='scoring_bal_striker_b4d5ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ball',
            unique_together={('innings', 'ball_number')},
        ),
        migrations.AddIndex(
            model_name='ballanalytics',
            index=models.Index(fields=['delivery_type'], name='scoring_bal_deliver_e011e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ballanalytics',
            index=models.Index(fields=['stroke'], name='scoring_bal_stroke_efd9db_idx'),
        ),
        migrations.AddIndex(
            model_name='ballreleasedata',
            index=models.Index(fields=['ball'], name='scoring_bal_ball_id_898ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='ballreleasedata',
            index=models.Index(fields=['bowler_release_position'], name='scoring_bal_bowler__ec7fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='ballspatialoutcome',
            index=models.Index(fields=['ball'], name='scoring_bal_ball_id_199836_idx'),
        ),
        migrations.AddIndex(
            model_name='balltrajectory',
            index=models.Index(fields=['ball', 'sequence_index'], name='scoring_bal_ball_id_b494b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='balltrajectory',
            unique_together={('ball', 'sequence_index')},
        ),
        migrations.AddIndex(
            model_name='ballvideo',
            index=models.Index(fields=['video_source_id'], name='scoring_bal_video_s_1d8697_idx'),
        ),
        migrations.AddIndex(
            model_name='ballvideo',
            index=models.Index(fields=['ball'], name='scoring_bal_ball_id_4db8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='ballwicket',
            index=models.Index(fields=['wicket_type'], name='scoring_bal_wicket__79de74_idx'),
        ),
        migrations.AddIndex(
            model_name='ballwicket',
            index=models.Index(fields=['dismissed_player'], name='scoring_bal_dismiss_c9dcfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batterstats',
            unique_together={('innings', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='bowlerstats',
            unique_together={('innings', 'player')},
        ),
    ]
