# Generated by Django 5.2.4 on 2026-01-20 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ball',
            options={'ordering': ['innings', 'ball_number']},
        ),
        migrations.RenameField(
            model_name='ball',
            old_name='bowler_runs',
            new_name='runs_off_bat',
        ),
        migrations.RenameField(
            model_name='inningsaggregate',
            old_name='balls',
            new_name='legal_balls',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='is_bye',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='is_leg_bye',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='is_no_ball',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='is_wide',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='striker_runs',
        ),
        migrations.RemoveField(
            model_name='ball',
            name='team_runs',
        ),
        migrations.AddField(
            model_name='ball',
            name='ball_in_over',
            field=models.PositiveIntegerField(default=1, help_text='1-based delivery count within the over'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ball',
            name='is_legal_delivery',
            field=models.BooleanField(default=True, help_text='Counts towards legal ball count'),
        ),
        migrations.AddField(
            model_name='inningsaggregate',
            name='completed_overs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inningsaggregate',
            name='is_chasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inningsaggregate',
            name='max_overs',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Revised max overs for innings (interruptions)', null=True),
        ),
        migrations.AddField(
            model_name='inningsaggregate',
            name='revised_target_runs',
            field=models.PositiveIntegerField(blank=True, help_text='DLS / manual revised target', null=True),
        ),
        migrations.AddField(
            model_name='inningsaggregate',
            name='target_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inningsaggregate',
            name='target_runs',
            field=models.PositiveIntegerField(blank=True, help_text='Target runs for chase (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='ball',
            name='ball_number',
            field=models.PositiveIntegerField(help_text='Sequential delivery order within the innings'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='edit_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ball',
            name='no_ball_type',
            field=models.CharField(blank=True, help_text='overstep / height / free-hit etc.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ball',
            name='over_number',
            field=models.PositiveIntegerField(help_text='1-based over number'),
        ),
        migrations.AlterField(
            model_name='batterstats',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bowlerstats',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inningsaggregate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inningsaggregate',
            name='last_ball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scoring.ball'),
        ),
    ]
