# Generated by Django 6.0 on 2026-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='completed_runs',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of runs physically completed by running'),
        ),
    ]
