# Generated by Codex on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0003_ball_quick_running_free_hit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballspatialoutcome",
            name="pitch_zone",
            field=models.CharField(
                blank=True,
                help_text="Pitch zone selected from matrix",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ballspatialoutcome",
            name="stump_zone",
            field=models.CharField(
                blank=True,
                help_text="Stump zone selected from matrix",
                max_length=20,
                null=True,
            ),
        ),
    ]

