# Generated by Codex on 2026-02-13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("coredata", "0004_stadium_floodlights_count"),
        ("scoring", "0004_ball_spatial_pitch_stump"),
    ]

    operations = [
        migrations.CreateModel(
            name="BallFielding",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("action", models.CharField(blank=True, max_length=50, null=True)),
                ("fielding_position", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ball", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="fielding", to="scoring.ball")),
                ("fielder1", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fielding_primary", to="coredata.player")),
                ("fielder2", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="fielding_secondary", to="coredata.player")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["action"], name="scoring_bal_action_0c52c6_idx"),
                    models.Index(fields=["fielding_position"], name="scoring_bal_fieldin_1c76ef_idx"),
                ],
            },
        ),
    ]

