# Generated by Codex on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0005_ball_fielding"),
    ]

    operations = [
        migrations.AddField(
            model_name="ball",
            name="bowler_hand",
            field=models.CharField(choices=[("LEFT", "Left"), ("RIGHT", "Right")], default="RIGHT", max_length=5),
        ),
        migrations.AddField(
            model_name="ball",
            name="striker_hand",
            field=models.CharField(choices=[("LEFT", "Left"), ("RIGHT", "Right")], default="RIGHT", max_length=5),
        ),
    ]

