# Generated by Codex on 2026-02-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coredata", "0004_stadium_floodlights_count"),
        ("scoring", "0006_ball_handedness"),
    ]

    operations = [
        migrations.AddField(
            model_name="ball",
            name="umpire_bowler_end",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="balls_bowler_end",
                to="coredata.umpire",
            ),
        ),
        migrations.AddField(
            model_name="ball",
            name="umpire_square_leg",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="balls_square_leg",
                to="coredata.umpire",
            ),
        ),
    ]

