# Generated by Codex on 2026-02-13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("coredata", "0004_stadium_floodlights_count"),
        ("scoring", "0007_ball_umpires"),
    ]

    operations = [
        migrations.CreateModel(
            name="BallDRS",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("is_appealed", models.BooleanField(default=False)),
                ("review_team_side", models.CharField(blank=True, help_text="BAT or BOWL", max_length=10, null=True)),
                ("on_field_decision", models.CharField(blank=True, choices=[("WICKET", "Wicket"), ("NOT_OUT", "Not Out"), ("WIDE", "Wide"), ("NO_BALL", "No Ball"), ("LEGAL", "Legal Ball")], max_length=20, null=True)),
                ("overruled", models.BooleanField(default=False)),
                ("final_decision", models.CharField(blank=True, choices=[("WICKET", "Wicket"), ("NOT_OUT", "Not Out"), ("WIDE", "Wide"), ("NO_BALL", "No Ball"), ("LEGAL", "Legal Ball")], max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ball", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="drs", to="scoring.ball")),
                ("review_team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="drs_reviews", to="coredata.team")),
            ],
        ),
    ]

