# Generated by Codex on 2026-02-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coredata", "0004_stadium_floodlights_count"),
        ("scoring", "0008_ball_drs"),
    ]

    operations = [
        migrations.AddField(
            model_name="balldrs",
            name="decision_given_by_umpire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drs_decisions_given",
                to="coredata.umpire",
            ),
        ),
        migrations.AddField(
            model_name="balldrs",
            name="third_umpire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drs_third_umpire",
                to="coredata.umpire",
            ),
        ),
    ]

