# Generated by Codex on 2026-02-13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_match_ci_id_drs_floodlights"),
        ("coredata", "0004_stadium_floodlights_count"),
        ("scoring", "0009_ball_drs_umpires"),
    ]

    operations = [
        migrations.AddField(
            model_name="inningsaggregate",
            name="extra_penalty_runs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="InningsPenalty",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("awarded_to", models.CharField(choices=[("BATTING", "Batting"), ("BOWLING", "Bowling")], max_length=10)),
                ("reason", models.CharField(max_length=100)),
                ("reason_other", models.CharField(blank=True, default="", max_length=200)),
                ("runs", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("awarded_team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="penalties_awarded", to="coredata.team")),
                ("awarded_to_innings", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="penalties_awarded", to="matches.innings")),
                ("innings", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="penalties_happened", to="matches.innings")),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="penalties", to="matches.match")),
            ],
        ),
    ]

