# Generated by Codex on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0010_innings_penalty_and_agg_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballfielding",
            name="runs_saved",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ballfielding",
            name="runs_misfielded",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ballfielding",
            name="overthrow_runs",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]

