# Generated by Django 6.0 on 2026-03-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_ball_spatial_structured'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ballfielding',
            new_name='scoring_bal_action_c79d75_idx',
            old_name='scoring_bal_action_0c52c6_idx',
        ),
        migrations.RenameIndex(
            model_name='ballfielding',
            new_name='scoring_bal_fieldin_e690e9_idx',
            old_name='scoring_bal_fieldin_1c76ef_idx',
        ),
    ]
