# Generated by Django 6.0 on 2026-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0014_rename_crease_movement_add_air_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballspatialoutcome',
            name='height_zone',
            field=models.CharField(blank=True, help_text='Height zone selected from matrix', max_length=20, null=True),
        ),
    ]
