# Generated by Django 6.0 on 2026-03-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0004_stadium_floodlights_count'),
        ('scoring', '0015_ballspatialoutcome_height_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballfielding',
            name='fielder1',
        ),
        migrations.AddField(
            model_name='ballfielding',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fielding_entries', to='coredata.player'),
        ),
        migrations.AlterField(
            model_name='ballfielding',
            name='ball',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldings', to='scoring.ball'),
        ),
    ]
