# Generated by Django 6.0 on 2026-03-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0016_remove_ballfielding_fielder1_ballfielding_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballreleasedata',
            name='ball_type',
            field=models.CharField(blank=True, help_text='New / Replacement ball', max_length=20, null=True),
        ),
    ]
