# Generated by Django 6.0 on 2026-03-31 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0005_umpire_role'),
        ('scoring', '0017_ballreleasedata_ball_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballwicket',
            name='decision_given_by_umpire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions_given', to='coredata.umpire'),
        ),
    ]
