# Generated by Django 5.2.4 on 2025-12-26 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_organization_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('USER', 'User'), ('ORG', 'Organization')], max_length=10)),
                ('owner_id', models.UUIDField()),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('DESKTOP', 'Desktop')], max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='accounts_de_owner_t_daeba3_idx')],
            },
        ),
    ]
