# Generated by Django 6.0 on 2026-01-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='allow_system_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allow_system_data',
            field=models.BooleanField(default=True),
        ),
    ]
