# Generated by Django 6.0 on 2026-01-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_device_allow_system_data_user_allow_system_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='allow_system_data',
        ),
    ]
