# Generated by Django 6.0 on 2026-01-28 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('season', models.CharField(blank=True, help_text='Season or year, e.g. 2024, 2024-25', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_entries', to='coredata.team')),
            ],
            options={
                'ordering': ['team__name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_squads', to='coredata.player')),
                ('competition_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='competitions.competitionteam')),
            ],
            options={
                'ordering': ['player__last_name', 'player__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('series_type', models.CharField(choices=[('BILATERAL', 'Bilateral'), ('TRI', 'Tri-series'), ('MULTI', 'Multi-team'), ('FRIENDLY', 'Friendly'), ('PRACTICE', 'Practice')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
                'indexes': [models.Index(fields=['series_type'], name='competition_series__18f521_idx'), models.Index(fields=['owner_type', 'owner_id'], name='competition_owner_t_07e3cf_idx')],
                'unique_together': {('name', 'owner_type', 'owner_id')},
            },
        ),
        migrations.CreateModel(
            name='SeriesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.series')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_entries', to='coredata.team')),
            ],
            options={
                'ordering': ['team__name'],
            },
        ),
        migrations.CreateModel(
            name='SeriesSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_squads', to='coredata.player')),
                ('series_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='competitions.seriesteam')),
            ],
            options={
                'ordering': ['player__last_name', 'player__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=50)),
                ('tournament_type', models.CharField(choices=[('INTERNATIONAL', 'International'), ('DOMESTIC', 'Domestic'), ('LEAGUE', 'League'), ('SCHOOL', 'School'), ('CLUB', 'Club')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='coredata.nationality')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='competitions.tournament'),
        ),
        migrations.AddIndex(
            model_name='competitionteam',
            index=models.Index(fields=['competition'], name='competition_competi_6b8942_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionteam',
            index=models.Index(fields=['team'], name='competition_team_id_9c6bd8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together={('competition', 'team')},
        ),
        migrations.AddIndex(
            model_name='competitionsquad',
            index=models.Index(fields=['competition_team'], name='competition_competi_264616_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionsquad',
            index=models.Index(fields=['player'], name='competition_player__e33b00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionsquad',
            unique_together={('competition_team', 'player')},
        ),
        migrations.AddIndex(
            model_name='seriesteam',
            index=models.Index(fields=['series'], name='competition_series__8b681c_idx'),
        ),
        migrations.AddIndex(
            model_name='seriesteam',
            index=models.Index(fields=['team'], name='competition_team_id_35f18c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seriesteam',
            unique_together={('series', 'team')},
        ),
        migrations.AddIndex(
            model_name='seriessquad',
            index=models.Index(fields=['series_team'], name='competition_series__772683_idx'),
        ),
        migrations.AddIndex(
            model_name='seriessquad',
            index=models.Index(fields=['player'], name='competition_player__5e6bc7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seriessquad',
            unique_together={('series_team', 'player')},
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['tournament_type'], name='competition_tournam_e578c5_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['nationality'], name='competition_nationa_898131_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together={('name', 'owner_type', 'owner_id')},
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['start_date'], name='competition_start_d_21ef3b_idx'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['owner_type', 'owner_id'], name='competition_owner_t_fae1d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together={('name', 'owner_type', 'owner_id')},
        ),
    ]
