# Generated by Django 6.0 on 2026-01-12 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coredata', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=50)),
                ('tournament_type', models.CharField(choices=[('INTERNATIONAL', 'International'), ('DOMESTIC', 'Domestic'), ('LEAGUE', 'League'), ('SCHOOL', 'School'), ('CLUB', 'Club')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='coredata.nationality')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tournament_type'], name='competition_tournam_e578c5_idx'), models.Index(fields=['nationality'], name='competition_nationa_898131_idx')],
                'unique_together': {('name', 'owner_type', 'owner_id')},
            },
        ),
    ]
