# Generated by Django 6.0 on 2026-01-12 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('season', models.CharField(blank=True, help_text='Season or year, e.g. 2024, 2024-25', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='competitions.tournament')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
                'indexes': [models.Index(fields=['start_date'], name='competition_start_d_21ef3b_idx'), models.Index(fields=['owner_type', 'owner_id'], name='competition_owner_t_fae1d7_idx')],
                'unique_together': {('name', 'owner_type', 'owner_id')},
            },
        ),
    ]
