# Generated by Django 6.0 on 2026-01-12 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition'),
        ('coredata', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='competitions.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_entries', to='coredata.team')),
            ],
            options={
                'ordering': ['team__name'],
                'indexes': [models.Index(fields=['competition'], name='competition_competi_6b8942_idx'), models.Index(fields=['team'], name='competition_team_id_9c6bd8_idx')],
                'unique_together': {('competition', 'team')},
            },
        ),
    ]
