# Generated by Django 6.0 on 2026-02-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_tournament_competition_series_fields'),
        ('coredata', '0004_stadium_floodlights_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='competitions', through='competitions.CompetitionTeam', to='coredata.team'),
        ),
        migrations.AddField(
            model_name='series',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='series', through='competitions.SeriesTeam', to='coredata.team'),
        ),
        migrations.AlterField(
            model_name='seriesteam',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_teams', to='competitions.series'),
        ),
    ]
