# Generated by Django 6.0 on 2026-01-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competitionteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
