# Generated by Django 6.0 on 2026-01-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_competition_is_locked'),
        ('coredata', '0005_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionteam',
            old_name='joined_at',
            new_name='added_at',
        ),
        migrations.CreateModel(
            name='CompetitionSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('competition_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='competitions.competitionteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_squads', to='coredata.player')),
            ],
            options={
                'ordering': ['player__last_name', 'player__first_name'],
                'indexes': [models.Index(fields=['competition_team'], name='competition_competi_264616_idx'), models.Index(fields=['player'], name='competition_player__e33b00_idx')],
                'unique_together': {('competition_team', 'player')},
            },
        ),
    ]
