# Generated by Django 6.0 on 2026-01-13 03:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_rename_joined_at_competitionteam_added_at_and_more'),
        ('coredata', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('series_type', models.CharField(choices=[('BILATERAL', 'Bilateral'), ('TRI', 'Tri-series'), ('MULTI', 'Multi-team'), ('FRIENDLY', 'Friendly'), ('PRACTICE', 'Practice')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
                'indexes': [models.Index(fields=['series_type'], name='competition_series__18f521_idx'), models.Index(fields=['owner_type', 'owner_id'], name='competition_owner_t_07e3cf_idx')],
                'unique_together': {('name', 'owner_type', 'owner_id')},
            },
        ),
        migrations.CreateModel(
            name='SeriesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.series')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_entries', to='coredata.team')),
            ],
            options={
                'ordering': ['team__name'],
            },
        ),
        migrations.CreateModel(
            name='SeriesSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_squads', to='coredata.player')),
                ('series_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='competitions.seriesteam')),
            ],
            options={
                'ordering': ['player__last_name', 'player__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='seriesteam',
            index=models.Index(fields=['series'], name='competition_series__8b681c_idx'),
        ),
        migrations.AddIndex(
            model_name='seriesteam',
            index=models.Index(fields=['team'], name='competition_team_id_35f18c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seriesteam',
            unique_together={('series', 'team')},
        ),
        migrations.AddIndex(
            model_name='seriessquad',
            index=models.Index(fields=['series_team'], name='competition_series__772683_idx'),
        ),
        migrations.AddIndex(
            model_name='seriessquad',
            index=models.Index(fields=['player'], name='competition_player__5e6bc7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seriessquad',
            unique_together={('series_team', 'player')},
        ),
    ]
