# Generated by Django 6.0 on 2026-01-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_plan_id_alter_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='toolUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
