# Generated by Django 6.0 on 2025-12-26 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(max_length=10)),
                ('owner_id', models.UUIDField()),
                ('device_id', models.UUIDField()),
                ('entity', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('sync_id', models.UUIDField()),
                ('payload', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('device_id', 'sync_id', 'operation')},
            },
        ),
    ]
