# Generated by Django 6.0 on 2026-01-28 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('nick_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('batting_hand', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5, null=True)),
                ('bowling_hand', models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5, null=True)),
                ('role', models.CharField(blank=True, choices=[('BATTER', 'Batter'), ('BOWLER', 'Bowler'), ('ALL_ROUNDER', 'All Rounder'), ('WICKET_KEEPER', 'Wicket Keeper')], max_length=20, null=True)),
                ('bowling_type', models.CharField(blank=True, choices=[('PACE', 'Pace'), ('MEDIUM', 'Medium Pace'), ('SPIN', 'Spin')], max_length=10, null=True)),
                ('batting_type', models.CharField(blank=True, choices=[('AGGRESSIVE', 'Aggressive'), ('ANCHOR', 'Anchor'), ('FINISHER', 'Finisher')], max_length=15, null=True)),
                ('batting_style', models.CharField(blank=True, max_length=100)),
                ('bowling_style', models.CharField(blank=True, max_length=100)),
                ('fielding_attributes', models.JSONField(default=dict)),
                ('wicket_keeping_skill', models.JSONField(default=dict)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='coredata.nationality')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='coredata_pl_last_na_743b8b_idx'), models.Index(fields=['nationality', 'role'], name='coredata_pl_nationa_fb6169_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stadiums', to='coredata.nationality')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'city', 'nationality')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=20)),
                ('team_type', models.CharField(choices=[('INTERNATIONAL', 'International'), ('DOMESTIC', 'Domestic'), ('LEAGUE', 'League')], max_length=20)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='coredata.nationality')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='coredata_te_name_ce2e2b_idx'), models.Index(fields=['team_type'], name='coredata_te_team_ty_7a9d0d_idx')],
                'unique_together': {('name', 'owner_type', 'owner_id')},
            },
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='umpires', to='coredata.nationality')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'nationality', 'owner_type', 'owner_id')},
            },
        ),
    ]
