# Generated by Django 6.0 on 2025-12-26 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stadiums', to='coredata.nationality')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'city', 'nationality')},
            },
        ),
    ]
