# Generated by Django 6.0 on 2026-01-12 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0004_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=20)),
                ('team_type', models.CharField(choices=[('INTERNATIONAL', 'International'), ('DOMESTIC', 'Domestic'), ('LEAGUE', 'League')], max_length=20)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='coredata.nationality')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='coredata_te_name_ce2e2b_idx'), models.Index(fields=['team_type'], name='coredata_te_team_ty_7a9d0d_idx')],
                'unique_together': {('name', 'owner_type', 'owner_id')},
            },
        ),
    ]
