# Generated by Django 6.0 on 2026-03-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0004_stadium_floodlights_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='umpire',
            name='role',
            field=models.CharField(choices=[('UMPIRE', 'Male'), ('REFEREE', 'Referee')], default='UMPIRE', max_length=10),
        ),
    ]
