# Generated by Django 6.0 on 2026-01-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0005_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batting_hand',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_hand',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(blank=True, choices=[('BATTER', 'Batter'), ('BOWLER', 'Bowler'), ('ALL_ROUNDER', 'All Rounder'), ('WICKET_KEEPER', 'Wicket Keeper')], max_length=20, null=True),
        ),
    ]
