# Generated by Django 6.0 on 2026-01-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_alter_stadium_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
