# Generated by Django 6.0 on 2026-01-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_id_alter_organizationinvite_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_system_data',
            field=models.BooleanField(default=True),
        ),
    ]
