# Generated by Django 6.0 on 2026-01-28 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('coredata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('balls_per_over', models.PositiveSmallIntegerField(default=6)),
                ('max_overs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_innings', models.PositiveSmallIntegerField(default=2)),
                ('allow_super_over', models.BooleanField(default=False)),
                ('allow_draw', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('owner_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('match_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=10)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('offline_snapshot_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.series')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.stadium')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team1', to='coredata.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team2', to='coredata.team')),
                ('umpires', models.ManyToManyField(blank=True, to='coredata.umpire')),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.matchtype')),
            ],
        ),
        migrations.CreateModel(
            name='PlayingXI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_position', models.PositiveSmallIntegerField()),
                ('is_captain', models.BooleanField(default=False)),
                ('is_wicket_keeper', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing_xis', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.team')),
            ],
            options={
                'ordering': ['batting_position'],
            },
        ),
        migrations.CreateModel(
            name='Toss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toss', to='matches.match')),
                ('won_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tosses_won', to='coredata.team')),
            ],
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.PositiveSmallIntegerField(help_text='Sequential innings number within the match')),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='OPEN', max_length=12)),
                ('is_super_over', models.BooleanField(default=False, help_text='True if this innings is a super over')),
                ('super_over_index', models.PositiveSmallIntegerField(blank=True, help_text='1,2,3... if super over', null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_batted', to='coredata.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_bowled', to='coredata.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='matches.match')),
            ],
            options={
                'ordering': ['innings_number'],
                'indexes': [models.Index(fields=['match', 'innings_number'], name='matches_inn_match_i_ceffc2_idx'), models.Index(fields=['match', 'state'], name='matches_inn_match_i_d75d41_idx')],
                'unique_together': {('match', 'innings_number')},
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['competition'], name='matches_mat_competi_f4b424_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['series'], name='matches_mat_series__9d6ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['state'], name='matches_mat_state_a1e979_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_mode'], name='matches_mat_match_m_cd0978_idx'),
        ),
        migrations.AddIndex(
            model_name='playingxi',
            index=models.Index(fields=['match', 'team'], name='matches_pla_match_i_27f5b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playingxi',
            unique_together={('match', 'team', 'player')},
        ),
        migrations.AddIndex(
            model_name='toss',
            index=models.Index(fields=['match'], name='matches_tos_match_i_549609_idx'),
        ),
    ]
