# Generated by Django 6.0 on 2026-01-13 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0006_series_seriesteam_seriessquad_and_more'),
        ('coredata', '0005_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('balls_per_over', models.PositiveSmallIntegerField(default=6)),
                ('max_overs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_innings', models.PositiveSmallIntegerField(default=2)),
                ('allow_super_over', models.BooleanField(default=False)),
                ('allow_draw', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('match_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=10)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('offline_snapshot_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.series')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coredata.stadium')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team1', to='coredata.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_team2', to='coredata.team')),
                ('umpires', models.ManyToManyField(blank=True, to='coredata.umpire')),
                ('match_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.matchtype')),
            ],
        ),
        migrations.CreateModel(
            name='PlayingXI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('is_captain', models.BooleanField(default=False)),
                ('is_wicket_keeper', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing_xis', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coredata.team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['competition'], name='matches_mat_competi_f4b424_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['series'], name='matches_mat_series__9d6ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['state'], name='matches_mat_state_a1e979_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_mode'], name='matches_mat_match_m_cd0978_idx'),
        ),
        migrations.AddIndex(
            model_name='playingxi',
            index=models.Index(fields=['match', 'team'], name='matches_pla_match_i_27f5b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playingxi',
            unique_together={('match', 'team', 'player')},
        ),
    ]
