# Generated by Django 6.0 on 2026-01-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playingxi',
            options={'ordering': ['batting_position']},
        ),
        migrations.RenameField(
            model_name='playingxi',
            old_name='position',
            new_name='batting_position',
        ),
    ]
