# Generated by Django 6.0 on 2026-03-31 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0005_umpire_role'),
        ('matches', '0002_match_ci_id_drs_floodlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_referee', to='coredata.umpire'),
        ),
        migrations.AddField(
            model_name='match',
            name='third_umpire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_third_ump', to='coredata.umpire'),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpires',
            field=models.ManyToManyField(blank=True, related_name='matches_umpires', to='coredata.umpire'),
        ),
    ]
