# Generated by Django 6.0 on 2026-01-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0005_team'),
        ('matches', '0002_alter_playingxi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.PositiveSmallIntegerField()),
                ('runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_batted', to='coredata.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='innings_bowled', to='coredata.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='matches.match')),
            ],
            options={
                'ordering': ['innings_number'],
                'indexes': [models.Index(fields=['match', 'innings_number'], name='matches_inn_match_i_ceffc2_idx')],
                'unique_together': {('match', 'innings_number')},
            },
        ),
        migrations.CreateModel(
            name='Toss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toss', to='matches.match')),
                ('won_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tosses_won', to='coredata.team')),
            ],
            options={
                'indexes': [models.Index(fields=['match'], name='matches_tos_match_i_549609_idx')],
            },
        ),
    ]
