# Generated by Django 5.2.4 on 2026-01-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0005_team'),
        ('matches', '0003_innings_toss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innings',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='innings',
            name='overs',
        ),
        migrations.RemoveField(
            model_name='innings',
            name='runs',
        ),
        migrations.RemoveField(
            model_name='innings',
            name='wickets',
        ),
        migrations.AddField(
            model_name='innings',
            name='is_super_over',
            field=models.BooleanField(default=False, help_text='True if this innings is a super over'),
        ),
        migrations.AddField(
            model_name='innings',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='OPEN', max_length=12),
        ),
        migrations.AddField(
            model_name='innings',
            name='super_over_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1,2,3... if super over', null=True),
        ),
        migrations.AlterField(
            model_name='innings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='innings',
            name='innings_number',
            field=models.PositiveSmallIntegerField(help_text='Sequential innings number within the match'),
        ),
        migrations.AlterField(
            model_name='innings',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playingxi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='toss',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='innings',
            index=models.Index(fields=['match', 'state'], name='matches_inn_match_i_d75d41_idx'),
        ),
    ]
