# Generated by Django 6.0 on 2026-01-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_innings_is_completed_remove_innings_overs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='playingxi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='toss',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
