# Generated by Django 6.0 on 2026-01-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_innings_id_alter_playingxi_id_alter_toss_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='owner_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='owner_type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('ORG', 'Organization')], default='SYSTEM', max_length=10),
        ),
    ]
